// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { PositionComponent, PositionComponentData, PositionComponentTableId } from "./tables/PositionComponent.sol";
import { GreedComponent, GreedComponentTableId } from "./tables/GreedComponent.sol";
import { HungerComponent, HungerComponentTableId } from "./tables/HungerComponent.sol";
import { StaminaComponent, StaminaComponentTableId } from "./tables/StaminaComponent.sol";
import { BraveryComponent, BraveryComponentTableId } from "./tables/BraveryComponent.sol";
import { HealthComponent, HealthComponentData, HealthComponentTableId } from "./tables/HealthComponent.sol";
import { SpeciesComponent, SpeciesComponentTableId } from "./tables/SpeciesComponent.sol";
import { DamageComponent, DamageComponentTableId } from "./tables/DamageComponent.sol";
import { TileComponent, TileComponentTableId } from "./tables/TileComponent.sol";
