// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { Greed, GreedTableId } from "./tables/Greed.sol";
import { Hunger, HungerTableId } from "./tables/Hunger.sol";
import { Bravery, BraveryTableId } from "./tables/Bravery.sol";
import { Exhaustion, ExhaustionTableId } from "./tables/Exhaustion.sol";
import { Health, HealthData, HealthTableId } from "./tables/Health.sol";
import { Species, SpeciesTableId } from "./tables/Species.sol";
import { Damage, DamageTableId } from "./tables/Damage.sol";
import { Armor, ArmorTableId } from "./tables/Armor.sol";
import { Tile, TileTableId } from "./tables/Tile.sol";
