// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum TileType {
  Fog,
  Ground,
  Wall,
  Door
}

enum Direction {
  Up,
  Left,
  Right,
  Down
}

enum Species {
  Sprite,
  Goblin,
  Dwarf,
  Dragon,
  Human
}
