// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { TileType } from "./../Types.sol";

interface IExploreSystem {
  function addTile(int8 x, int8 y, uint32 z, TileType tile) external;

  function addTiles(int8[] calldata x, int8[] calldata y, uint32 z, TileType[] calldata tile) external;
}
